name: e_shop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  carousel_slider: ^4.1.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  firebase_messaging: ^14.6.8
  google_sign_in: ^6.1.2
  uuid: ^3.0.6
  firebase_core_platform_interface: 4.8.0
  shared_preferences: ^2.1.0
  http: ^1.1.0
  flutter_local_notifications: ^15.1.1

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/logo/
    - assets/svgs/order/
    - assets/svgs/
    - assets/images/
