// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL9u81Aih8zuf-53Jw6s48CDFJOFGXZNw',
    appId: '1:5975695317:web:d69af20e38d8178c09e75c',
    messagingSenderId: '5975695317',
    projectId: 'flutter-e-shop-49ad1',
    authDomain: 'flutter-e-shop-49ad1.firebaseapp.com',
    storageBucket: 'flutter-e-shop-49ad1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6PT7P2VvQ8GNygHZ5aLAH2SjeNO3JtxM',
    appId: '1:5975695317:android:43bdf47086699ede09e75c',
    messagingSenderId: '5975695317',
    projectId: 'flutter-e-shop-49ad1',
    storageBucket: 'flutter-e-shop-49ad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH6A6F5yyps_dy5oCPFcitHZJkzyOI_Xo',
    appId: '1:5975695317:ios:ef40ed585fd4303a09e75c',
    messagingSenderId: '5975695317',
    projectId: 'flutter-e-shop-49ad1',
    storageBucket: 'flutter-e-shop-49ad1.appspot.com',
    androidClientId: '5975695317-ruptk6tnvkqifhqjo40j3c1pkn0q4rfb.apps.googleusercontent.com',
    iosClientId: '5975695317-roi2re0ggd68urlgtc72fhlu9lijoa84.apps.googleusercontent.com',
    iosBundleId: 'com.example.eShop',
  );
}
